[package]
name = "roxy-rules"
description = "Expression DSL, rule compiler and policy evaluator for roxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dashmap = "6.2.1"
globset = { version = "0.4.20", default-features = false }
humantime-serde.workspace = true
ipnet.workspace = true
parking_lot = "0.12.5"
regex.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion = { version = "0.7.0", default-features = false }
insta = "1.49.0"
proptest = "1.11.0"
serde_yaml_ng.workspace = true

[lints]
workspace = true

[[bench]]
name = "evaluate"
harness = false
