//! Raw bindings for the `roxy:addon/layer` world, generated by wit-bindgen.
//!
//! Most layers never need these: the rest of the crate wraps them. They are
//! public for anything the wrappers do not cover.

wit_bindgen::generate!({
    path: "wit",
    world: "roxy:addon/layer",
    generate_all,
    pub_export_macro: true,
    default_bindings_module: "roxy_addon::bindings",
});
