[package]
name = "roxy-tls"
description = "CA management and TLS configuration for roxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lru = "0.18.5"
pem.workspace = true
rcgen.workspace = true
ring.workspace = true
roxy-http.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring", "tls12", "std", "logging"] }
rustls-pki-types.workspace = true
thiserror.workspace = true
time.workspace = true
webpki-roots = "1.0.9"
x509-parser = { workspace = true, features = ["verify"] }

[dev-dependencies]
proptest = "1.11.0"
tempfile.workspace = true

[lints]
workspace = true
